# Generated by Django 3.1.5 on 2021-02-20 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_mode', models.IntegerField(default=301)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_of_sets_number', models.IntegerField(default=13)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_turn_score', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('number_of_180s', models.IntegerField(default=0)),
                ('lowest_turn_score', models.IntegerField(default=181)),
                ('number_of_turns', models.IntegerField(default=0)),
                ('score_remaining', models.IntegerField(default=301)),
                ('leg_wins', models.IntegerField(default=0)),
                ('set_wins', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=512)),
                ('current_league_rank', models.IntegerField()),
                ('average_season_score', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('average_lifetime_score', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('number_of_180s', models.IntegerField(default=0)),
                ('number_of_season_turns', models.IntegerField(default=0)),
                ('number_of_lifetime_turns', models.IntegerField(default=0)),
                ('number_of_legs_won', models.IntegerField(default=0)),
                ('number_of_legs_lost', models.IntegerField(default=0)),
                ('number_of_sets_won', models.IntegerField(default=0)),
                ('number_of_sets_lost', models.IntegerField(default=0)),
                ('number_of_matches_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_bust', models.BooleanField(default=False)),
                ('is_committed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.leg')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.matchplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_of_legs_number', models.IntegerField(default=5)),
                ('num_legs_complete', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.match')),
            ],
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player'),
        ),
        migrations.AddField(
            model_name='leg',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.match'),
        ),
        migrations.AddField(
            model_name='leg',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='backend.matchplayer'),
        ),
        migrations.AddField(
            model_name='leg',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='backend.matchplayer'),
        ),
        migrations.AddField(
            model_name='leg',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.set'),
        ),
        migrations.CreateModel(
            name='DartboardHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('is_bounce_out', models.BooleanField(default=False)),
                ('is_knock_out', models.BooleanField(default=False)),
                ('is_double', models.BooleanField(default=False)),
                ('is_triple', models.BooleanField(default=False)),
                ('is_bullseye', models.BooleanField(default=False)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.turn')),
            ],
        ),
    ]
