# Generated by Django 3.1.5 on 2021-02-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='leg_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='set',
            name='set_number',
            field=models.IntegerField(default=1),
        ),
    ]
