# Generated by Django 3.1.5 on 2021-03-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_set_and_leg_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='num_sets_complete',
            field=models.IntegerField(default=0),
        ),
    ]
