# Generated by Django 3.1.5 on 2021-04-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_match_num_sets_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='dartboardhit',
            name='is_foul',
            field=models.BooleanField(default=False),
        ),
    ]
