# Generated by Django 3.1.5 on 2021-04-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_doubles_and_triples'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='highest_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_win',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='lowest_turn_score',
            field=models.IntegerField(default=181),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_matches_list',
            field=models.IntegerField(default=0),
        ),
    ]
