# Generated by Django 3.1.5 on 2021-04-20 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_matches_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_win',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
